name: real_estate_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  sizer: ^2.0.15
  device_preview: ^1.1.0
  intl_phone_number_input: ^0.7.2
  google_maps_flutter: ^2.2.5
  pinput: ^2.2.31
  flutter_screenutil: ^5.9.3
  animate_do: ^3.3.4
  syncfusion_flutter_sliders: ^26.2.13
  syncfusion_flutter_charts: ^26.2.13
  syncfusion_flutter_core: # or an earlier version without the issue
  custom_navigation_bar: ^0.8.2
  calendar_date_picker2: ^0.5.3
  flutter_rating_bar: ^4.0.0  # Check for the latest version on pub.dev
  flutter_switch: ^0.3.2


  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/
  fonts:
    - family: RedHatDisplay
      fonts:
        - asset: assets/fonts/RedHatDisplay-VariableFont_wght.ttf
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-BlackItalic.ttf
